import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion } from 'motion/react';
import './styles.css';
import BlurText from './components/BlurText';
import DarkVeil from './component/DarkVeil';
import CardSwap, { Card } from './component/CardSwap';
import SpecularButton from './component/SpecularButton';

const skills = [
  { icon: '⌗', title: 'Orçamento & custos', count: '12 SKILLS', text: 'Do levantamento ao orçamento com referências que fazem sentido.', items: ['Composição SINAPI', 'BDI e encargos', 'Curva ABC'] },
  { icon: '⌁', title: 'Planejamento', count: '09 SKILLS', text: 'Transforme escopo solto em sequência de obra executável.', items: ['Cronograma físico', 'Caminho crítico', 'Histograma'] },
  { icon: '◫', title: 'Documentação', count: '11 SKILLS', text: 'Documentos técnicos claros, consistentes e prontos para revisar.', items: ['Memorial descritivo', 'Especificações', 'Relatórios'] },
  { icon: '✣', title: 'Análise & campo', count: '08 SKILLS', text: 'Apoio para decidir melhor antes de colocar a equipe em campo.', items: ['Laudos técnicos', 'Patologias', 'Checklists'] }
];
const commands = [
  ['ORÇAMENTO', 'Componha um custo SINAPI', 'Monte a composição e a memória de cálculo para este serviço.'],
  ['PLANEJAMENTO', 'Monte meu cronograma', 'Organize estas atividades por dependência e duração.'],
  ['DOCUMENTAÇÃO', 'Escreva um memorial', 'Transforme estas notas de projeto em um memorial claro.'],
  ['ANÁLISE', 'Leia este laudo', 'Aponte riscos, inconsistências e próximos passos neste documento.'],
  ['CAMPO', 'Crie um checklist', 'Gere um checklist de inspeção para esta etapa da obra.'],
  ['REVISÃO', 'Revise minha medição', 'Confira esta medição e liste o que precisa de evidência.']
];
const bonuses = [
  ['BÔNUS 01', 'Biblioteca de prompts', 'Os comandos essenciais já organizados por momento da obra.', 'R$ 97'],
  ['BÔNUS 02', 'Aula de contexto', 'Como dar contexto técnico para obter respostas que ajudam de verdade.', 'R$ 147'],
  ['BÔNUS 03', 'Templates de campo', 'Modelos editáveis para acelerar inspeções, reuniões e entregas.', 'R$ 197']
];

function SplitText({ text, className = '' }) { return <span className={`split-text ${className}`}>{text.split(' ').map((word, index) => <span className="split-word" style={{ '--i': index }} key={`${word}-${index}`}>{word}&nbsp;</span>)}</span>; }
function ArrowIcon({ className = '' }) { return <svg className={`arrow-icon ${className}`} width="46" height="46" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14" /><path d="m13 18 6-6" /><path d="m13 6 6 6" /></svg>; }
function BonusIcon({ type }) {
  const paths = [
    <><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" /><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z" /><path d="M8 7h8M8 11h6" /></>,
    <><path d="M3 4h18" /><path d="M12 4v16" /><path d="m8 20 4-4 4 4" /><rect x="5" y="7" width="14" height="7" rx="1" /></>,
    <><path d="M9 5h6" /><path d="M9 4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2H9V4Z" /><rect x="5" y="5" width="14" height="16" rx="2" /><path d="m9 13 2 2 4-4" /></>
  ];
  return <svg className="bonus-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" aria-hidden="true">{paths[type]}</svg>;
}
function SkillIcon({ type }) {
  const paths = [
    <><rect x="4" y="3" width="16" height="18" rx="2" /><path d="M8 7h8M8 11h2M14 11h2M8 15h2M14 15h2M8 18h8" /></>,
    <><circle cx="6" cy="18" r="2" /><circle cx="18" cy="6" r="2" /><path d="M8 18h2a4 4 0 0 0 4-4v-4a4 4 0 0 1 4-4" /></>,
    <><path d="M5 4h10l4 4v12H5z" /><path d="M15 4v5h4M8 13h8M8 17h6" /></>,
    <><path d="M4 19V5M4 19h16" /><path d="m7 15 3-4 3 2 5-7" /><path d="M18 6h2v2" /></>
  ];
  return <svg className="skill-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" aria-hidden="true">{paths[type]}</svg>;
}
function AnimatedContent({ children, className = '', delay = 0 }) { return <motion.div className={className} initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-80px' }} transition={{ duration: 0.7, delay, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>; }
function DocumentMockup() { return <div className="mockup-wrap"><div className="mockup-note">PRUMO / WORKFLOW 001</div><CardSwap width={430} height={360} cardDistance={30} verticalDistance={40} delay={3000} pauseOnHover={false}><Card className="workflow-card"><span className="workflow-kicker">01 / ORÇAMENTO</span><h3>Composição<br /><em>SINAPI</em></h3><p>“Monte a memória de cálculo para este serviço.”</p><span className="workflow-foot">12 SKILLS DISPONÍVEIS <ArrowIcon /></span></Card><Card className="workflow-card"><span className="workflow-kicker">02 / DOCUMENTAÇÃO</span><h3>Memorial<br /><em>descritivo</em></h3><p>“Transforme estas notas em um documento claro.”</p><span className="workflow-foot">11 SKILLS DISPONÍVEIS <ArrowIcon /></span></Card><Card className="workflow-card"><span className="workflow-kicker">03 / PLANEJAMENTO</span><h3>Cronograma<br /><em>físico</em></h3><p>“Organize as atividades por dependência e duração.”</p><span className="workflow-foot">09 SKILLS DISPONÍVEIS <ArrowIcon /></span></Card></CardSwap></div>; }

function App() {
  const [showSticky, setShowSticky] = useState(false); const offerRef = useRef(null);
  useEffect(() => { const onScroll = () => setShowSticky(window.scrollY > 700); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll); }, []);
  const goOffer = () => offerRef.current?.scrollIntoView({ behavior: 'smooth' });
  return <div className="site-shell">
    <div className="topbar"><span className="brick">▦</span> TURMA FUNDADORA <span className="topbar-dot">•</span> CONDIÇÃO ESPECIAL DE LANÇAMENTO <span className="topbar-end">VAGAS LIMITADAS</span></div>
    <header className="hero dark-section"><div className="hero-darkveil-background" aria-hidden="true"><DarkVeil hueShift={223} noiseIntensity={0.04} scanlineFrequency={0.5} warpAmount={5} /></div><div className="engineer-rule"><span>01</span><span>05</span><span>10</span><span>15</span><span>20</span></div><div className="hero-watermark">01</div><nav><a className="brand" href="#inicio"><span className="brand-mark">⌟</span> PRUMO<span className="brand-light">.CIVIL</span></a><div className="nav-links"><a href="#pacote">O pacote</a><a href="#como-funciona">Como funciona</a><a href="#faq">Dúvidas</a></div><button className="nav-cta" onClick={goOffer}>Quero conhecer <ArrowIcon /></button></nav><div className="hero-grid" id="inicio"><div className="hero-copy"><div className="eyebrow accent">INTELIGÊNCIA ARTIFICIAL PARA ENGENHARIA</div><h1>Mais prumo para<br /><span>o seu trabalho.</span></h1><BlurText text="Um pacote de skills e comandos prontos para quem projeta, orça e constrói. Menos tarefa repetitiva. Mais tempo para o que só você pode fazer." className="hero-lead" /><div className="hero-actions"><SpecularButton size="lg" radius={9} tint="#ff3e00" tintOpacity={0} blur={14} textColor="#d56a47" lineColor="#ff784c" baseColor="#d56a47" intensity={3} shineSize={10} shineFade={35} thickness={1} speed={0.35} followMouse proximity={250} autoAnimate onClick={goOffer}>Quero trabalhar com mais prumo <ArrowIcon /></SpecularButton><span className="action-note">Acesso imediato<br />para Claude</span></div><div className="hero-trust"><span><b>↯</b> ACESSO IMEDIATO</span><span><b>◷</b> 7 DIAS DE GARANTIA</span><span><b>+</b> 700 COMANDOS</span></div></div><DocumentMockup /></div><div className="scroll-cue"><span />ROLE PARA CONHECER</div></header>
    <div className="ticker" aria-hidden="true"><div className="ticker-track">ORÇAMENTO <b>✳</b> SINAPI <b>✳</b> BDI <b>✳</b> CRONOGRAMA <b>✳</b> LAUDO <b>✳</b> MEMORIAL <b>✳</b> OBRA <b>✳</b> ORÇAMENTO <b>✳</b> SINAPI <b>✳</b> BDI <b>✳</b> CRONOGRAMA <b>✳</b> LAUDO <b>✳</b> MEMORIAL <b>✳</b> OBRA <b>✳</b></div></div>
    <main>
      <section className="section pain-section"><AnimatedContent><div className="section-label">01 / O PROBLEMA</div><div className="pain-layout"><div><h2>Seu tempo não deveria<br />sumir em <span>tarefa repetida.</span></h2></div><div className="body-copy"><p>Levantar quantitativo. Procurar composição. Revisar memorial. Montar cronograma. Responder a mesma dúvida pela terceira vez.</p><p>Você estudou para tomar decisões técnicas — mas boa parte do dia escorre em tarefas que poderiam começar prontas.</p><strong className="pivot">Tempo perdido é<br /><em>dinheiro que não volta.</em></strong></div></div><div className="callout"><span className="quote-mark">“</span><p>“Já tentei usar um ChatGPT genérico. Ele não entende a realidade da obra.”</p><b>É por isso que o Prumo não começa pela IA.<br /><span>Começa pelo seu contexto.</span></b></div></AnimatedContent></section>
      <section className="bridge"><span>↓</span><p>E se a ferramenta já soubesse<br /><em>como a engenharia funciona?</em></p></section>
      <section className="section tinted mechanism" id="como-funciona"><AnimatedContent><div className="section-label">02 / O MECANISMO</div><h2>Contexto técnico<br /><span>embutido em cada skill.</span></h2><p className="wide-copy">O Prumo é um pacote de instruções especializadas para Claude. Cada skill carrega o raciocínio, os critérios e o vocabulário que você usa no dia a dia da engenharia civil.</p><div className="split-note"><span>VOCÊ DÁ A DIREÇÃO</span><b>+</b><span>O PRUMO ORGANIZA O CAMINHO</span><i><ArrowIcon className="arrow-down-right" /></i></div></AnimatedContent></section>
      <section className="section" id="pacote"><AnimatedContent><div className="section-head"><div><div className="section-label">03 / O PACOTE</div><h2>Uma caixa de ferramentas<br /><span>para toda a obra.</span></h2></div><p>40 skills pensadas para acompanhar o profissional do primeiro levantamento à entrega final.</p></div><div className="skills-grid">{skills.map((skill, i) => <motion.article className="skill-card" key={skill.title} whileHover={{ y: -6 }} transition={{ duration: .2 }}><div className="card-icon"><SkillIcon type={i} /></div><div className="card-count">{skill.count}</div><h3>{skill.title}</h3><p>{skill.text}</p><ul>{skill.items.map(item => <li key={item}>↳ {item}</li>)}</ul><span className="card-index">0{i + 1}</span></motion.article>)}</div><button className="text-link" onClick={goOffer}>Ver tudo que vem no pacote <ArrowIcon /></button></AnimatedContent></section>
      <section className="section tinted commands"><AnimatedContent><div className="section-label">04 / NA PRÁTICA</div><div className="section-head"><h2>700 comandos.<br /><span>Um ponto de partida.</span></h2><p>Para transformar uma página em branco em um próximo passo claro, sem ficar encarando o cursor piscando.</p></div><div className="command-grid">{commands.map(([tag, title, text], i) => <article className="command-card" key={title}><span className="command-tag">{tag}</span><span className="command-number">0{i + 1}</span><h3>{title}</h3><p>{text}</p><span className="command-arrow"><ArrowIcon /></span></article>)}</div><p className="under-note">+ 694 comandos para as outras situações que aparecem no caminho.</p></AnimatedContent></section>
      <section className="section steps"><AnimatedContent><div className="section-label">05 / SEM COMPLICAÇÃO</div><h2>Comece em <span>3 passos.</span></h2><div className="steps-grid">{[['01', 'Copie o pacote', 'Você recebe o acesso e instala as skills no Claude em poucos minutos.'], ['02', 'Dê o contexto', 'Conte sobre seu projeto, sua etapa e o que precisa resolver.'], ['03', 'Trabalhe melhor', 'Use o tempo recuperado para revisar, decidir e construir.']].map(([number, title, text]) => <div className="step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></AnimatedContent></section>
      <section className="section tinted bonuses"><AnimatedContent><div className="section-head"><div><div className="section-label">06 / AINDA VEM</div><h2>Mais valor para<br /><span>começar direito.</span></h2></div><p>Além das skills, materiais para encurtar a curva entre ter acesso e sentir resultado.</p></div><div className="bonus-grid">{bonuses.map(([label, title, text, price], index) => <article className="bonus" key={label}><span className="eyebrow">{label}</span><div className="bonus-art"><BonusIcon type={index} /></div><h3>{title}</h3><p>{text}</p><div className="bonus-price"><s>{price}</s><b>GRÁTIS</b></div></article>)}</div></AnimatedContent></section>
      <section className="section offer-section dark-section" ref={offerRef} id="oferta"><AnimatedContent><div className="offer-layout"><div className="offer-intro"><div className="eyebrow orange">CONDIÇÃO DE FUNDADOR</div><h2>Trabalhe com<br /><span>mais prumo.</span></h2><p>O pacote completo para trazer clareza, velocidade e contexto técnico para o seu dia.</p><div className="offer-manifesto">“Você assina.<br /><em>A ferramenta não.</em>”</div></div><div className="offer-card"><div className="offer-card-top"><span>PRUMO CIVIL</span><span>ACESSO VITALÍCIO</span></div><p className="offer-desc">40 skills + 700 comandos + todos os bônus</p><div className="price"><div><s>R$ 997</s><small>70% OFF</small></div><strong><sup>R$</sup>297</strong><span>pagamento único</span></div><ul className="checklist">{['40 skills especializadas', '700 comandos prontos', 'Biblioteca de prompts', '3 aulas de ativação', 'Templates de campo', 'Comunidade fechada'].map(item => <li key={item}>✓ {item}</li>)}</ul><p className="value-note">Menos que uma hora do seu tempo técnico.<br /><strong>Mas devolve muitas.</strong></p><button className="button button-orange" onClick={() => alert('O checkout será conectado em breve.')}>Quero o Prumo Civil <ArrowIcon /></button><small className="secure">⌁ Compra segura · Acesso imediato</small></div></div></AnimatedContent></section>
      <section className="section guarantee"><AnimatedContent><div className="guarantee-box"><div className="guarantee-icon">7</div><div><div className="eyebrow">GARANTIA DE USO REAL</div><h3>Teste no seu próximo documento.</h3><p>Você tem 7 dias para abrir as skills, usar em uma situação real e decidir. Se não fizer sentido para seu trabalho, é só pedir o reembolso.</p></div><span className="guarantee-arrow"><ArrowIcon /></span></div><div className="stamp-row"><div className="stamp">PRUMO<br /><strong>✦</strong><br /><span>VOCÊ ASSINA · A FERRAMENTA NÃO</span></div><p>Inteligência apoia sua decisão.<br /><strong>A responsabilidade continua sendo sua.</strong></p></div></AnimatedContent></section>
      <section className="section reposition"><AnimatedContent><div className="section-label">07 / UM LEMBRETE</div><p>O Prumo não ensina engenharia. Também não substitui sua experiência, sua assinatura ou seu julgamento.</p><h2>Ele tira o peso do caminho<br />para você enxergar <span>mais longe.</span></h2></AnimatedContent></section>
      <section className="section tinted testimonials"><AnimatedContent><div className="section-head"><div><div className="section-label">08 / GENTE REAL</div><h2>O que vem depois<br /><span>do começo.</span></h2></div><p className="placeholder-note">O Prumo acabou de nascer. Estes espaços já estão reservados para as histórias de quem construir essa próxima fase com a gente.</p></div><div className="testimonial-grid">{['O antes e depois de um orçamento real.', 'Como uma equipe incorporou o Prumo no dia a dia.', 'A decisão que ficou mais simples com contexto.'].map((text, i) => <div className="testimonial" key={text}><span>“</span><p>[ {text} ]</p><small>DEPOIMENTO DA TURMA FUNDADORA · 0{i + 1}</small></div>)}</div></AnimatedContent></section>
      <section className="section faq" id="faq"><AnimatedContent><div className="section-label">09 / DÚVIDAS</div><div className="faq-layout"><h2>Antes de<br /><span>começar.</span></h2><div>{[['Funciona no plano gratuito do Claude?', 'Sim. O pacote foi desenhado para funcionar no Claude, inclusive no plano gratuito, respeitando os limites da sua conta.'], ['Isso é um curso de engenharia?', 'Não. É uma caixa de ferramentas para profissionais que já conhecem seu trabalho.'], ['É só um monte de prompts soltos?', 'Não. As skills carregam contexto, critérios e uma forma de pensar específica para a engenharia civil.'], ['Como recebo o acesso?', 'Logo após a confirmação do pagamento, você recebe o material e as instruções por e-mail.'], ['E se eu não gostar?', 'Você tem 7 dias para testar em uma situação real e pedir o reembolso, sem complicação.']].map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></AnimatedContent></section>
      <section className="section final-cta dark-section"><AnimatedContent><div className="section-label orange">10 / O PRÓXIMO PASSO</div><h2>Você pode continuar<br />fazendo tudo <span>no braço.</span></h2><p>Ou começar a trabalhar com mais prumo, hoje.</p><button className="button button-orange" onClick={goOffer}>Quero conhecer o pacote <ArrowIcon /></button><small>R$ 297 à vista · 7 dias de garantia</small></AnimatedContent></section>
      <section className="section ps"><AnimatedContent><div className="ps-card"><span>P.S.</span><p>Cada hora que você devolve para o trabalho técnico é uma hora a mais para revisar aquela decisão importante, conversar com o cliente ou simplesmente ir embora no horário.</p><strong>Seu tempo tem prumo.</strong></div></AnimatedContent></section>
    </main>
    <footer className="footer dark-section"><a className="brand" href="#inicio"><span className="brand-mark">⌟</span> PRUMO<span className="brand-light">.CIVIL</span></a><p>Ferramentas de inteligência artificial para profissionais da engenharia civil.<br />O Prumo Civil é um produto independente e não possui vínculo institucional com a Anthropic. Não substitui responsabilidade técnica.</p><small>© 2026 PRUMO CIVIL. TODOS OS DIREITOS RESERVADOS.</small></footer>
    <motion.div className={`sticky-bar ${showSticky ? 'visible' : ''}`} initial={false} animate={{ y: showSticky ? 0 : 100 }}><div><strong>PRUMO CIVIL</strong><span>40 skills + 700 comandos</span></div><b>R$ 297</b><button onClick={goOffer}>Quero o pacote <ArrowIcon /></button></motion.div>
  </div>;
}

createRoot(document.getElementById('root')).render(<App />);